In [2]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd
import numpy as np

# 1、归一化 x' = x-min/max-min      x''=x'*(max-min)+min

# 适用于高精度小规模数据，容易受到异常点的影响

In [4]:
data = pd.read_csv('./data/datingtest/dating.txt')
data.head(5)

milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1

In [5]:
partitions = ['milage', 'Liters', 'Consumtime']

In [6]:
data = data[partitions]
data.head(5)

milage     Liters  Consumtime
0   40920   8.326976    0.953952
1   14488   7.153469    1.673904
2   26052   1.441871    0.805124
3   75136  13.147394    0.428964
4   38344   1.669788    0.134296

In [10]:
mm = MinMaxScaler(feature_range=(0,1))

In [11]:
data = mm.fit_transform(data)
print(data)

[[0.44832535 0.39805139 0.56233353]
 [0.15873259 0.34195467 0.98724416]
 [0.28542943 0.06892523 0.47449629]
 ...
 [0.29115949 0.50910294 0.51079493]
 [0.52711097 0.43665451 0.4290048 ]
 [0.47940793 0.3768091  0.78571804]]


# 2、标准化 x' = (x-mean)/σ σ是标准差

# 在已有样本足够多的情况下比较稳定，适合现代嘈杂大数据场景

In [12]:
dating = pd.read_csv('./data/datingtest/dating.txt')
dating.head(5)

milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1

In [13]:
std = StandardScaler()

In [16]:
dating = dating[partitions]
dating.head(10)

milage     Liters  Consumtime
0   40920   8.326976    0.953952
1   14488   7.153469    1.673904
2   26052   1.441871    0.805124
3   75136  13.147394    0.428964
4   38344   1.669788    0.134296
5   72993  10.141740    1.032955
6   35948   6.830792    1.213192
7   42666  13.276369    0.543880
8   67497   8.631577    0.749278
9   35483  12.273169    1.508053

In [18]:
dating = std.fit_transform(dating)
print(dating)

[[ 0.33193158  0.41660188  0.24523407]
 [-0.87247784  0.13992897  1.69385734]
 [-0.34554872 -1.20667094 -0.05422437]
 ...
 [-0.32171752  0.96431572  0.06952649]
 [ 0.65959911  0.60699509 -0.20931587]
 [ 0.46120328  0.31183342  1.00680598]]
